name: CI/CD Pipeline for brosch-predictive-maintenance backend applicaion

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    #1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Load environment variables (from secrets only)
    - name: Load environment variables
      run: |
        echo "AWS_REGION=${{secrets.AWS_REGION}}" >> $GITHUB_ENV
        echo "ECR_REGISTRY=${{secrets.ECR_REGISTRY}}" >> $GITHUB_ENV
        echo "ECR_REPOSITORY=${{secrets.ECR_REPOSITORY}}" >> $GITHUB_ENV

        echo "BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN=${{ secrets.BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=${{ secrets.BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN }}" >> $GITHUB_ENV
    # 3. Configure AWS Credentials (ONLY for Github to ECR push)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    #4. Login to ECR (Github side)
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_REGISTRY

    # 5. Build Docker image
    - name: Build Docker image
      run: |
       docker build -t $ECR_REPOSITORY .
      
    # 6. Tag docker image
    - name: Tag Docker image
      run: | 
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # 7. Push image to ECR
    - name: Push image to ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # 8. Deploy to EC2 (NO AWS KEYS HERE)
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.6
      env:
        BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN: ${{ secrets.BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN,MLFLOW_TRACKING_USERNAME,MLFLOW_TRACKING_PASSWORD
        script: |
          set -e

          echo "Stopping old container..."
          docker stop fastapi-app || true
          docker rm fastapi-app || true

          echo "Logging into ECR using IAM role..."
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

          echo "Pulling latest image..."
          docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

          echo "Running new container..."
          docker run -d \
            -p 8000:8000 \
            --name fastapi-app \
            --restart unless-stopped \
            -e BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN="$BOSCH_PREDICTION_ENV_DAGSHUB_TOKEN" \
            -e MLFLOW_TRACKING_USERNAME="$MLFLOW_TRACKING_USERNAME" \
            -e MLFLOW_TRACKING_PASSWORD="$MLFLOW_TRACKING_PASSWORD" \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest